config/routes.rb
Rails.application.routes.draw do 
	root 'pages#home'
  
  # controller "pages" do
  # 	get 'stone'
	# 	get 'case'
  # end

  resources :stones, only: [:show, :index]
  resources :examples, only: [:show, :index]
  resources :techniques, only: [:show, :index]

  post "/inquire", to: "mails#inquire"

  namespace "admin" do
    get "/", to: redirect('/admin/stones')
    resources :tabs, only: [:index, :edit, :update]
    resources :tabs_titles, only: [:index, :edit, :update]
  	resources :stones
  	resources :examples
  	resources :techniques
    controller "ads" do
      post 'ads/toggle', as: "toggle_ads"
    end
    resources :attachments, only: [:destroy] do
      member do
        post "set_cover"
      end      
    end
  end
  
  devise_for :admins

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	def send_devise_notification(notification, *args)
	  devise_mailer.send(notification, self, *args).deliver_later
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	belongs_to :imageable, polymorphic: true
	mount_uploader :image, ImageUploader
	scope :cover, -> { where(cover: true).limit(1) }

	after_save :make_sure_cover_exist!

	def make_sure_cover_exist!
		unless self.imageable.attachments.cover.present?
			self.update(cover: true) # 如果第一次就上傳多張的話，就剛好設定最後一張是封面～
		end
	end
end

app/models/example.rb
class Example < ApplicationRecord
	has_many :example_and_stones, dependent: :destroy
	has_many :stones, through: :example_and_stones
	has_many :attachments, as: :imageable, dependent: :destroy

	validates :zh_name, presence: true

	include Expressive

	enum ad_status: { ad_off: 0, ad_on: 1 }
end

app/models/example_and_stone.rb
class ExampleAndStone < ApplicationRecord
  belongs_to :stone
  belongs_to :example
end

app/models/stone.rb
class Stone < ApplicationRecord
	has_many :example_and_stones, dependent: :destroy
	has_many :examples, through: :example_and_stones
	has_many :technique_and_stones, dependent: :destroy
	has_many :techniques, through: :technique_and_stones
	has_many :attachments, as: :imageable, dependent: :destroy

	validates :zh_name, presence: true

	include Expressive

	enum ad_status: { ad_off: 0, ad_on: 1 }
end

app/models/tab.rb
class Tab < ApplicationRecord
	validates :title, presence: true
end

app/models/tabs_title.rb
class TabsTitle < ApplicationRecord
	validates :title, presence: true
end

app/models/technique.rb
class Technique < ApplicationRecord
	has_many :technique_and_stones, dependent: :destroy
	has_many :stones, through: :technique_and_stones
	has_many :attachments, as: :imageable, dependent: :destroy

	validates :zh_name, presence: true

	include Expressive
end

app/models/technique_and_stone.rb
class TechniqueAndStone < ApplicationRecord
  belongs_to :stone
  belongs_to :technique
end

app/controllers/admin/tabs_titles_controller.rb
class Admin::TabsTitlesController < AdminController
	before_action :find_tabs_title, except: [:index]
	def index
		@tabs_title = TabsTitle.first
	end

  def edit
  end

  def update
  	if @tabs_title.update(tabs_title_params)
  		flash[:success] = "更新成功"
  		redirect_to admin_tabs_titles_path
  	else
  		render :edit
  	end
  end

  private

  def find_tabs_title
  	@tabs_title = TabsTitle.find(params[:id])
  end

  def tabs_title_params
  	params.require(:tabs_title).permit(:title, :description)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_admin!
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def index
  	@examples = Example.all
  end

  def show
  	@example = Example.find(params[:id])
  end
end

app/controllers/mails_controller.rb
class MailsController < ActionController::Base
	def inquire
		UserMailer.inquire_mail(
			params[:name],
			params[:contact],
			params[:availability],
			params[:content]
		).deliver_later
		redirect_to root_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@tabs_title = TabsTitle.first
  	@tabs = Tab.all.order(:priority).limit(5)
  	ad_stone_ids = Stone.ad_on.order("RANDOM()").limit(6).pluck(:id)
  	@top_ad_stones = Stone.find(ad_stone_ids.first(3))
  	@bottom_ad_stones = Stone.find(ad_stone_ids.last(3))
  	@ad_examples = Example.ad_on.order("RANDOM()").limit(5)
  end
end

app/controllers/stones_controller.rb
class StonesController < ApplicationController
  def index
  	@stones = Stone.all
  end

  def show
  	@stone = Stone.find(params[:id])
  end
end

app/helpers/admin/tabs_titles_helper.rb
module Admin::TabsTitlesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
	def render_tab_icons
		return { "glyphicon-home": 1, "glyphicon-thumbs-up": 2, "glyphicon-wrench": 3, "glyphicon-heart": 4, "glyphicon-briefcase": 5 }
	end
end

app/helpers/alerts_helper.rb
module AlertsHelper
  def notice_message
    if flash.any?
      alerts = flash.map do |type, message|
        alert_div message, type
      end
      alerts.join("\n").html_safe
    end
  end

  def alert_div(message, type="info")
    return capture do
      content_tag :div, class: "alert alert-#{type} mt-1 mb-1" do
        message
      end
    end
  end

  def form_errors(obj)
    if obj.errors.any?
      obj.errors.full_messages.map do |message|
        alert_div message, "danger"
      end.join("\n").html_safe
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def render_scroll_class_when_needed
		current_page?(root_path)? 'scroll' : ''
	end

	def render_active(path)
		current_page?(path) ? "active" : ""
	end
end

app/helpers/examples_helper.rb
module ExamplesHelper
	def render_wrapper_direction(num)
		case num % 4
		when 0
			return "event-left fadeInLeft"
		when 1
			return "event-right fadeInRight"
		when 2
			return "event-left event-left1 fadeInRight"
		when 3
			return "event-right event-right1 fadeInLeft"
		end
	end

	def render_content_direction(num)
		case num % 4
		when 0
			return "event-top"
		when 1
			return "event-top event-top1"
		when 2
			return "event-top event-t"
		when 3
			return "event-top event-t1"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stones_helper.rb
module StonesHelper
end

app/views/admin/tabs_titles/_form.html.erb
<%= form_for ["admin", @tabs_title], html: { multipart: true } do |f| %>
	<%= form_errors(@tabs_title) %>
	<div class="form-group">
		<%= f.label :title, class: "required" %>
		<%= f.text_field :title, class: "form-control", required: true %>	
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: "form-control", rows: 7 %>
	</div>
	<label class="hvr-rectangle-out agileits w3layouts">
		<%= f.submit "儲存", data: { disable_with: "資料上傳中..." } %>
	</label>
<% end %>

app/views/admin/tabs_titles/_tabs_title.html.erb
<tr>
	<td><span class="glyphicon agileits w3layouts <%= tabs_ttile.icon %>" aria-hidden="true"></span></td>
	<td><%= tabs_ttile.title %></td>
	<td style="width: 40%;"><%= simple_format tabs_ttile.description %></td>
	<td><%= tabs_ttile.priority %></td>
	<td style="white-space: nowrap;">
		<%= link_to "編輯", edit_admin_tabs_title_path(tabs_ttile), class: "btn btn-primary btn-sm" %> 
	</td>
</tr>

app/views/admin/tabs_titles/edit.html.erb
<div class="container" style="margin-bottom: 15px;">
	<h2 style="margin-bottom: 10px;">修改歡迎文字</h2>
	<%= render "form" %>
</div>

app/views/admin/tabs_titles/index.html.erb
<h2>
	首頁列表
</h2>
<div class="table-responsive">
<table class="table table-hover">
	<thead>
		<tr>
			<th>歡迎標題</th>
			<th>敘述</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% if @tabs_title.present? %>
			<tr>
				<td><%= @tabs_title.title %></td>
				<td style="width: 40%;"><%= simple_format @tabs_title.description %></td>
				<td style="white-space: nowrap;">
					<%= link_to "編輯", edit_admin_tabs_title_path(@tabs_title), class: "btn btn-primary btn-sm" %> 
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
</div>