config/routes.rb
Rails.application.routes.draw do 
	root 'pages#home'
  
  # controller "pages" do
  # 	get 'stone'
	# 	get 'case'
  # end

  resources :stones, only: [:show, :index]
  resources :examples, only: [:show, :index]
  resources :techniques, only: [:show, :index]

  post "/inquire", to: "mails#inquire"

  namespace "admin" do
    get "/", to: redirect('/admin/stones')
    resources :tabs, only: [:index, :edit, :update]
    resources :tabs_titles, only: [:index, :edit, :update]
  	resources :stones
  	resources :examples
  	resources :techniques
    controller "ads" do
      post 'ads/toggle', as: "toggle_ads"
    end
    resources :attachments, only: [:destroy] do
      member do
        post "set_cover"
      end      
    end
  end
  
  devise_for :admins

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	def send_devise_notification(notification, *args)
	  devise_mailer.send(notification, self, *args).deliver_later
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	belongs_to :imageable, polymorphic: true
	mount_uploader :image, ImageUploader
	scope :cover, -> { where(cover: true).limit(1) }

	after_save :make_sure_cover_exist!

	def make_sure_cover_exist!
		unless self.imageable.attachments.cover.present?
			self.update(cover: true) # 如果第一次就上傳多張的話，就剛好設定最後一張是封面～
		end
	end
end

app/models/example.rb
class Example < ApplicationRecord
	has_many :example_and_stones, dependent: :destroy
	has_many :stones, through: :example_and_stones
	has_many :attachments, as: :imageable, dependent: :destroy

	validates :zh_name, presence: true

	include Expressive

	enum ad_status: { ad_off: 0, ad_on: 1 }
end

app/models/example_and_stone.rb
class ExampleAndStone < ApplicationRecord
  belongs_to :stone
  belongs_to :example
end

app/models/stone.rb
class Stone < ApplicationRecord
	has_many :example_and_stones, dependent: :destroy
	has_many :examples, through: :example_and_stones
	has_many :technique_and_stones, dependent: :destroy
	has_many :techniques, through: :technique_and_stones
	has_many :attachments, as: :imageable, dependent: :destroy

	validates :zh_name, presence: true

	include Expressive

	enum ad_status: { ad_off: 0, ad_on: 1 }
end

app/models/tab.rb
class Tab < ApplicationRecord
	validates :title, presence: true
end

app/models/tabs_title.rb
class TabsTitle < ApplicationRecord
	validates :title, presence: true
end

app/models/technique.rb
class Technique < ApplicationRecord
	has_many :technique_and_stones, dependent: :destroy
	has_many :stones, through: :technique_and_stones
	has_many :attachments, as: :imageable, dependent: :destroy

	validates :zh_name, presence: true

	include Expressive
end

app/models/technique_and_stone.rb
class TechniqueAndStone < ApplicationRecord
  belongs_to :stone
  belongs_to :technique
end

app/controllers/admin/techniques_controller.rb
class Admin::TechniquesController < AdminController
	before_action :find_technique, only: [:edit, :update, :destroy, :show]
	def index
		@techniques = Technique.all
	end

	def new
		@technique = Technique.new
	end

	def create
		@technique = Technique.new(technique_params)
		if @technique.save
			if params[:images].present?
				params[:images].each { |image| @technique.attachments.create({image: image}) }
			else
				flash[:warning] = "請記得上傳圖片。"	
			end
			flash[:success] = "新增成功。"
			redirect_to admin_techniques_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @technique.update(technique_params)
			if params[:images].present?
				params[:images].each { |image| @technique.attachments.create({image: image}) }
			end
			flash[:success] = "更新成功。"
			redirect_to admin_techniques_path
		else
			render :edit
		end
	end

	def destroy
		if @technique.destroy
			flash[:success] = "已刪除。"
			redirect_to admin_techniques_path
		end
	end


	private

	def find_technique
		@technique = Technique.find(params[:id])
	end

	def technique_params
		params.require(:technique).permit(:id, :zh_name, :en_name, :description, stone_ids: [])
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_admin!
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def index
  	@examples = Example.all
  end

  def show
  	@example = Example.find(params[:id])
  end
end

app/controllers/mails_controller.rb
class MailsController < ActionController::Base
	def inquire
		UserMailer.inquire_mail(
			params[:name],
			params[:contact],
			params[:availability],
			params[:content]
		).deliver_later
		redirect_to root_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@tabs_title = TabsTitle.first
  	@tabs = Tab.all.order(:priority).limit(5)
  	ad_stone_ids = Stone.ad_on.order("RANDOM()").limit(6).pluck(:id)
  	@top_ad_stones = Stone.find(ad_stone_ids.first(3))
  	@bottom_ad_stones = Stone.find(ad_stone_ids.last(3))
  	@ad_examples = Example.ad_on.order("RANDOM()").limit(5)
  end
end

app/controllers/stones_controller.rb
class StonesController < ApplicationController
  def index
  	@stones = Stone.all
  end

  def show
  	@stone = Stone.find(params[:id])
  end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  def index
  	@techniques = Technique.all
  end

  def show
  	@technique = Technique.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
	def render_tab_icons
		return { "glyphicon-home": 1, "glyphicon-thumbs-up": 2, "glyphicon-wrench": 3, "glyphicon-heart": 4, "glyphicon-briefcase": 5 }
	end
end

app/helpers/alerts_helper.rb
module AlertsHelper
  def notice_message
    if flash.any?
      alerts = flash.map do |type, message|
        alert_div message, type
      end
      alerts.join("\n").html_safe
    end
  end

  def alert_div(message, type="info")
    return capture do
      content_tag :div, class: "alert alert-#{type} mt-1 mb-1" do
        message
      end
    end
  end

  def form_errors(obj)
    if obj.errors.any?
      obj.errors.full_messages.map do |message|
        alert_div message, "danger"
      end.join("\n").html_safe
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def render_scroll_class_when_needed
		current_page?(root_path)? 'scroll' : ''
	end

	def render_active(path)
		current_page?(path) ? "active" : ""
	end
end

app/helpers/examples_helper.rb
module ExamplesHelper
	def render_wrapper_direction(num)
		case num % 4
		when 0
			return "event-left fadeInLeft"
		when 1
			return "event-right fadeInRight"
		when 2
			return "event-left event-left1 fadeInRight"
		when 3
			return "event-right event-right1 fadeInLeft"
		end
	end

	def render_content_direction(num)
		case num % 4
		when 0
			return "event-top"
		when 1
			return "event-top event-top1"
		when 2
			return "event-top event-t"
		when 3
			return "event-top event-t1"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stones_helper.rb
module StonesHelper
end

app/views/admin/techniques/_form.html.erb
<%= form_for ["admin", @technique], html: { multipart: true } do |f| %>
	<%= form_errors(@technique) %>
	<% if @technique.attachments.present? %>
		<div class="row">
			<%= render partial: "admin/attachments/attachments", collection: @technique.attachments, as: :attachment %>
		</div>
		<hr>
	<% end %>
	<div class="form-group">
		<label for="images[]">上傳圖片</label>
		<%= file_field_tag "images[]", multiple: true %>
	</div>
	<div class="form-group">
		<%= f.label :zh_name, class: "required" %>
		<%= f.text_field :zh_name, class: "form-control", required: true %>	
	</div>
	<div class="form-group">
		<%= f.label :en_name %>
		<%= f.text_field :en_name, class: "form-control" %>	
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: "form-control", rows: 7 %>
	</div>
	<div class="form-group">
		<%= f.label :stone_ids %>
		<%= f.collection_select :stone_ids, Stone.all, :id, :zh_name, {}, class: "form-control select2",  multiple: "multiple" %>
	</div>
	<label class="hvr-rectangle-out agileits w3layouts">
		<%= f.submit "儲存", data: { disable_with: "資料上傳中..." } %>
	</label>
<% end %>

app/views/admin/techniques/_technique.html.erb
<tr>
	<td><%= technique.zh_name %></td>
	<td><%= technique.en_name %></td>
	<td style="width: 33%;"><%= simple_format technique.description %></td>
	<td style="white-space: nowrap;">
		<%= link_to "編輯", edit_admin_technique_path(technique), class: "btn btn-primary btn-sm" %> |
		<%= link_to "刪除", admin_technique_path(technique), method: :delete, data: { confirm: "確定要刪除嗎？" }, class: "btn btn-danger btn-sm" %>
	</td>
</tr>

app/views/admin/techniques/edit.html.erb
<div class="container" style="margin-bottom: 15px;">
	<h2 style="margin-bottom: 10px;">修改工法資料</h2>
	<%= render "form" %>
</div>

app/views/admin/techniques/index.html.erb
<h2>
	工法列表
	<%= link_to "新增", new_admin_technique_path, class: "btn btn-success" %>
</h2>
<div class="table-responsive">
<table class="table table-hover">
	<thead>
		<tr>
			<th>中文名稱</th>
			<th>英文名稱</th>
			<th>敘述</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<%= render @techniques %>
	</tbody>
</table>
</div>

app/views/admin/techniques/new.html.erb
<div class="container" style="margin-bottom: 15px;">
	<h2 style="margin-bottom: 10px;">新增工法</h2>
	<%= render "form" %>
</div>

app/views/techniques/index.html.erb
<div class="event" id="events">
	<div class="container">
		<div class="top-event">
			<h3>石材工法</h3>
		</div>
		<%= @techniques.each_slice(4) do |te4| %>
			<% te4.each_with_index do |te, i| %>
				<div class="<%= i.even? ? 'event-grid' : '' %>">
					<div class="wow <%= render_wrapper_direction(i) %> animated" data-wow-delay=".5s">
						<%= link_to te do %>
							<%= image_tag (te.attachments.cover.try(:first).try(:image).try(:url) || "default.svg"), class: "img-responsive" %>
						<% end %>
						<div class="<%= render_content_direction(i) %>">
							<div class="event-gr">
								<h4><%= link_to te.full_name, te %></h4>
								<p><%= truncate(te.description.to_s, length: 49) %></p>
								<% if te.description.to_s.length >= 49 %>
									<div class="text-right">
										<%= link_to "More", te, style: "cursor: pointer; color: #8ec21f;" %>
									</div>
								<% end %>
							</div>
						</div>
					</div>
					<% if i.odd? %>
						<div class="clearfix"></div>
					<% end %>
				</div>
			<% end %>
		<% end %>
		<div class="clearfix"></div>
	</div>
</div>

app/views/techniques/show.html.erb
<div class="single agileits w3layouts">
  <div class="container">
    <div class="top-stone">
      <h3><%= @technique.full_name %></h3>
    </div>
        
    <div class="single-top col-md-9 col-sm-12">
      <div class="col-sm-12 team-grid wow fadeInLeft animated" data-wow-delay=".5s">
        <div class="col-1">
          <% if @technique.attachments.present? %>
            <% @technique.attachments.each do |attachment| %>
              <%= image_tag attachment.image.url, class: "img-responsive gray" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="lone-line col-sm-12 wow fadeInLeft animated" data-wow-delay=".5s">
        <ul class="grid-blog agileits w3layouts">
          <%= simple_format @technique.description %>
        </ul>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="col-1-at md-word sidebar-title-wrapper">
        <h5 class="text-center sidebar-title"><a href="single.html">適用石材</a></h5>
      </div>
      <%= render partial: "sidebar/stone", collection: @technique.stones, as: :stone %>
    </div>
  </div>      
</div>