config/routes.rb
Rails.application.routes.draw do 
	root 'pages#home'
  
  # controller "pages" do
  # 	get 'stone'
	# 	get 'case'
  # end

  resources :stones, only: [:show, :index]
  resources :examples, only: [:show, :index]
  resources :techniques, only: [:show, :index]

  post "/inquire", to: "mails#inquire"

  namespace "admin" do
    get "/", to: redirect('/admin/stones')
    resources :tabs, only: [:index, :edit, :update]
    resources :tabs_titles, only: [:index, :edit, :update]
  	resources :stones
  	resources :examples
  	resources :techniques
    controller "ads" do
      post 'ads/toggle', as: "toggle_ads"
    end
    resources :attachments, only: [:destroy] do
      member do
        post "set_cover"
      end      
    end
  end
  
  devise_for :admins

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	def send_devise_notification(notification, *args)
	  devise_mailer.send(notification, self, *args).deliver_later
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	belongs_to :imageable, polymorphic: true
	mount_uploader :image, ImageUploader
	scope :cover, -> { where(cover: true).limit(1) }

	after_save :make_sure_cover_exist!

	def make_sure_cover_exist!
		unless self.imageable.attachments.cover.present?
			self.update(cover: true) # 如果第一次就上傳多張的話，就剛好設定最後一張是封面～
		end
	end
end

app/models/example.rb
class Example < ApplicationRecord
	has_many :example_and_stones, dependent: :destroy
	has_many :stones, through: :example_and_stones
	has_many :attachments, as: :imageable, dependent: :destroy

	validates :zh_name, presence: true

	include Expressive

	enum ad_status: { ad_off: 0, ad_on: 1 }
end

app/models/example_and_stone.rb
class ExampleAndStone < ApplicationRecord
  belongs_to :stone
  belongs_to :example
end

app/models/stone.rb
class Stone < ApplicationRecord
	has_many :example_and_stones, dependent: :destroy
	has_many :examples, through: :example_and_stones
	has_many :technique_and_stones, dependent: :destroy
	has_many :techniques, through: :technique_and_stones
	has_many :attachments, as: :imageable, dependent: :destroy

	validates :zh_name, presence: true

	include Expressive

	enum ad_status: { ad_off: 0, ad_on: 1 }
end

app/models/tab.rb
class Tab < ApplicationRecord
	validates :title, presence: true
end

app/models/tabs_title.rb
class TabsTitle < ApplicationRecord
	validates :title, presence: true
end

app/models/technique.rb
class Technique < ApplicationRecord
	has_many :technique_and_stones, dependent: :destroy
	has_many :stones, through: :technique_and_stones
	has_many :attachments, as: :imageable, dependent: :destroy

	validates :zh_name, presence: true

	include Expressive
end

app/models/technique_and_stone.rb
class TechniqueAndStone < ApplicationRecord
  belongs_to :stone
  belongs_to :technique
end

app/controllers/admin/examples_controller.rb
class Admin::ExamplesController < AdminController
	before_action :find_example, only: [:edit, :update, :destroy, :show]
	def index
		@examples = Example.order(id: :desc).all
	end

	def new
		@example = Example.new
	end

	def create
		@example = Example.new(example_params)
		if @example.save
			if params[:images].present?
				params[:images].each { |image| @example.attachments.create({image: image}) }
			else
				flash[:warning] = "請記得上傳圖片。"	
			end
			flash[:success] = "新增成功。"
			redirect_to admin_examples_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @example.update(example_params)
			if params[:images].present?
				params[:images].each { |image| @example.attachments.create({image: image}) }
			end
			flash[:success] = "更新成功。"
			redirect_to admin_examples_path
		else
			render :edit
		end
	end

	def destroy
		if @example.destroy
			flash[:success] = "已刪除。"
			redirect_to admin_examples_path
		end
	end


	private

	def find_example
		@example = Example.find(params[:id])
	end

	def example_params
		params.require(:example).permit(:id, :zh_name, :en_name, :date_and_time, :description, :ad_status, stone_ids: [])
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def index
  	@examples = Example.all
  end

  def show
  	@example = Example.find(params[:id])
  end
end

app/controllers/mails_controller.rb
class MailsController < ActionController::Base
	def inquire
		UserMailer.inquire_mail(
			params[:name],
			params[:contact],
			params[:availability],
			params[:content]
		).deliver_later
		redirect_to root_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@tabs_title = TabsTitle.first
  	@tabs = Tab.all.order(:priority).limit(5)
  	ad_stone_ids = Stone.ad_on.order("RANDOM()").limit(6).pluck(:id)
  	@top_ad_stones = Stone.find(ad_stone_ids.first(3))
  	@bottom_ad_stones = Stone.find(ad_stone_ids.last(3))
  	@ad_examples = Example.ad_on.order("RANDOM()").limit(5)
  end
end

app/controllers/stones_controller.rb
class StonesController < ApplicationController
  def index
  	@stones = Stone.all
  end

  def show
  	@stone = Stone.find(params[:id])
  end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  def index
  	@techniques = Technique.all
  end

  def show
  	@technique = Technique.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
	def render_tab_icons
		return { "glyphicon-home": 1, "glyphicon-thumbs-up": 2, "glyphicon-wrench": 3, "glyphicon-heart": 4, "glyphicon-briefcase": 5 }
	end
end

app/helpers/alerts_helper.rb
module AlertsHelper
  def notice_message
    if flash.any?
      alerts = flash.map do |type, message|
        alert_div message, type
      end
      alerts.join("\n").html_safe
    end
  end

  def alert_div(message, type="info")
    return capture do
      content_tag :div, class: "alert alert-#{type} mt-1 mb-1" do
        message
      end
    end
  end

  def form_errors(obj)
    if obj.errors.any?
      obj.errors.full_messages.map do |message|
        alert_div message, "danger"
      end.join("\n").html_safe
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def render_scroll_class_when_needed
		current_page?(root_path)? 'scroll' : ''
	end

	def render_active(path)
		current_page?(path) ? "active" : ""
	end
end

app/helpers/examples_helper.rb
module ExamplesHelper
	def render_wrapper_direction(num)
		case num % 4
		when 0
			return "event-left fadeInLeft"
		when 1
			return "event-right fadeInRight"
		when 2
			return "event-left event-left1 fadeInRight"
		when 3
			return "event-right event-right1 fadeInLeft"
		end
	end

	def render_content_direction(num)
		case num % 4
		when 0
			return "event-top"
		when 1
			return "event-top event-top1"
		when 2
			return "event-top event-t"
		when 3
			return "event-top event-t1"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stones_helper.rb
module StonesHelper
end

app/views/admin/examples/_example.html.erb
<tr>
	<td><%= example.zh_name %></td>
	<td><%= example.en_name %></td>
	<td><%= example.date_and_time %></td>
	<td><%= simple_format example.description %></td>
	<td style="white-space: nowrap;">
		<% if example.ad_off? %>
			<%= link_to "設為首頁精選", admin_toggle_ads_path(model: "Example", id: example.id), class: "btn btn-info btn-sm", method: :post %> |
		<% else %>
			<%= link_to "取消首頁精選", admin_toggle_ads_path(model: "Example", id: example.id), class: "btn btn-default btn-sm", method: :post %> |
		<% end %>
		<%= link_to "編輯", edit_admin_example_path(example), class: "btn btn-primary btn-sm" %> |
		<%= link_to "刪除", admin_example_path(example), method: :delete, data: { confirm: "確定要刪除嗎？" }, class: "btn btn-danger btn-sm" %>
	</td>
</tr>

app/views/admin/examples/_form.html.erb
<%= form_for ["admin", @example], html: { multipart: true } do |f| %>
	<%= form_errors(@example) %>
	<% if @example.attachments.present? %>
		<div class="row">
			<%= render partial: "admin/attachments/attachments", collection: @example.attachments, as: :attachment %>
		</div>
		<hr>
	<% end %>
	<div class="form-group">
		<label for="images[]">上傳圖片</label>
		<%= file_field_tag "images[]", multiple: true %>
	</div>
	<div class="form-group">
		<%= f.label :zh_name, class: "required" %>
		<%= f.text_field :zh_name, class: "form-control", required: true %>	
	</div>
	<div class="form-group">
		<%= f.label :en_name %>
		<%= f.text_field :en_name, class: "form-control" %>	
	</div>
	<div class="form-group">
		<%= f.label :date_and_time %>
		<%= f.text_field :date_and_time, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: "form-control", rows: 7 %>
	</div>
	<div class="form-group">
		<%= f.label :stone_ids %>
		<%= f.collection_select :stone_ids, Stone.all, :id, :zh_name, {}, class: "form-control select2",  multiple: "multiple" %>
	</div>
	<label class="hvr-rectangle-out agileits w3layouts">
		<%= f.submit "儲存", data: { disable_with: "資料上傳中..." } %>
	</label>
<% end %>

app/views/admin/examples/edit.html.erb
<div class="container" style="margin-bottom: 15px;">
	<h2 style="margin-bottom: 10px;">修改案例資料</h2>
	<%= render "form" %>
</div>

app/views/admin/examples/index.html.erb
<% unless Example.ad_on.size >= 5 %>
	<div class="alert alert-warning mt-1 mb-1">請至少設定 5 個精選案例，避免首頁顯示錯誤。</div>
<% end %>
<h2>
	案例列表
	<%= link_to "新增", new_admin_example_path, class: "btn btn-success" %>
</h2>
<div class="table-responsive">
<table class="table table-hover">
	<thead>
		<tr>
			<th>中文名稱</th>
			<th>英文名稱</th>
			<th>完成日期或是製作時間長短</th>
			<th style="width: 33%;">敘述</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<%= render @examples %>
	</tbody>
</table>
</div>

app/views/admin/examples/new.html.erb
<div class="container" style="margin-bottom: 15px;">
	<h2 style="margin-bottom: 10px;">新增案例</h2>
	<%= render "form" %>
</div>